gcloud compute networks create net-03 --project=pitechplus-training-project --subnet-mode=custom --mtu=1460 --bgp-routing-mode=regional

gcloud compute networks subnets create us-central-one --project=pitechplus-training-project --range=10.0.0.0/9 --network=net-03 --region=europe-west4

gcloud compute networks subnets create us-central-two --project=pitechplus-training-project --range=10.0.0.0/9 --network=net-03 --region=europe-west6

gcloud compute instances create my-vm-us2 --project=pitechplus-training-project --zone=us-central1-c --machine-type=e2-medium --network-interface=network-tier=PREMIUM,subnet=net-03-sub-00 --maintenance-policy=MIGRATE --service-account=1038095267221-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --create-disk=auto-delete=yes,boot=yes,device-name=my-vm-us2,image=projects/debian-cloud/global/images/debian-10-buster-v20210916,mode=rw,size=10,type=projects/pitechplus-training-project/zones/us-central1-a/diskTypes/pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any

gcloud compute instances create my-vm-us3 --project=pitechplus-training-project --zone=us-west1-c --machine-type=e2-medium --network-interface=network-tier=PREMIUM,subnet=net-03-sub-00 --maintenance-policy=MIGRATE --service-account=1038095267221-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --create-disk=auto-delete=yes,boot=yes,device-name=my-vm-us3,image=projects/debian-cloud/global/images/debian-10-buster-v20210916,mode=rw,size=10,type=projects/pitechplus-training-project/zones/us-central1-a/diskTypes/pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any

